// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// var Dual1 = DefineSlot[string]()
// var Dual2 = DefineSlot[string]()

// templ DualSlot() {
// 	<h1>
// 		@Dual1 {
// 			{ children... }
// 		}
// 	</h1>
// 	<p>
// 		@Dual2 {
// 			{ children... }
// 		}
// 	</p>
// }

//	templ TStoryTest() {
//		@TStory() {
//			@title.Template() {
//				<span>testing slot with no params</span>
//			}
//			@content.Template() {
//				<span>slot with no params worked</span>
//			}
//		}
//	}
var _ = templruntime.GeneratedTemplate
